import asyncio
import struct
from bleak import BleakClient

# --- Hardware Configuration ---
MAC_ADDRESS = "A1:B2:CC:09:78:0F"  # Your watch MAC
WRITE_UUID   = "0000b002-0000-1000-8000-00805f9b34fb"
NOTIFY_UUID  = "0000b001-0000-1000-8000-00805f9b34fb"

# Dictionary to store responsive opcodes discovered during the scan
discovered_telemetry = {}

def build_packet(opcode: int, payload: bytes = b"") -> bytes:
    """Constructs standard [Length (2B)] + [Opcode (1B)] + [Payload] packets."""
    total_length = len(payload) + 3
    return struct.pack("<H", total_length) + bytes([opcode]) + payload

def scan_notification_handler(sender, data: bytearray):
    """Intercepts and records any responsive telemetry generated by the watch."""
    if len(data) < 5:
        return

    # Check for ZK MTU wrapping (0x00FF)
    if data[0] == 0x00 and data[1] == 0xFF:
        opcode = data[4]
        payload = data[5:]
    else:
        opcode = data[2] if len(data) > 2 else 0
        payload = data[3:] if len(data) > 3 else b""

    # Store the result
    if opcode not in discovered_telemetry:
        discovered_telemetry[opcode] = []
    discovered_telemetry[opcode].append(payload.hex())

    print(f"\n[!!! TELEMETRY HIT !!!] Watch responded to Opcode: 0x{opcode:02X}")
    print(f"  ├── Raw Payload: {payload.hex()}")
    
    # Try ASCII decode
    try:
        ascii_str = payload.decode("utf-8", errors="ignore").rstrip("\x00").strip()
        if any(c.isalnum() for c in ascii_str) and len(ascii_str) > 1:
            print(f"  └── ASCII Decode: '{ascii_str}'")
    except Exception:
        pass

async def main():
    print(f"[*] Initializing Automated Telemetry Scanner on [{MAC_ADDRESS}]...")
    async with BleakClient(MAC_ADDRESS, timeout=15.0) as client:
        if not client.is_connected:
            print("[-] Connection failed.")
            return
            
        print("[+] Link active. Binding notification channel...")
        await client.start_notify(NOTIFY_UUID, scan_notification_handler)
        await asyncio.sleep(0.5)

        # 1. Unlock command gate
        print("[>] Executing Master Handshake (0x78)...")
        await client.write_gatt_char(WRITE_UUID, build_packet(0x78, b"\x01\x00"), response=False)
        await asyncio.sleep(0.8)

        # 2. Stabilize clock
        print("[>] Injecting System Time Sync (0x68)...")
        await client.write_gatt_char(WRITE_UUID, build_packet(0x68, bytes.fromhex("48ff536a201c00020000")), response=False)
        await asyncio.sleep(0.8)

        print("\n--- [ Phase 1: Sweeping Opcodes with Empty Payload (b'') ] ---")
        # Test common command boundaries (0x01 to 0x3F are primary sensor/info registers)
        for opcode in range(0x01, 0x40):
            print(f"\r[*] Testing Opcode: 0x{opcode:02X}...", end="", flush=True)
            await client.write_gatt_char(WRITE_UUID, build_packet(opcode, b""), response=False)
            await asyncio.sleep(0.4) # Rapid sweep; watch replies instantly to valid reads

        print("\n\n--- [ Phase 2: Sweeping Opcodes with Read Flag (b'\\x00') ] ---")
        for opcode in range(0x60, 0x90):
            print(f"\r[*] Testing Opcode: 0x{opcode:02X}...", end="", flush=True)
            await client.write_gatt_char(WRITE_UUID, build_packet(opcode, b"\x00"), response=False)
            await asyncio.sleep(0.4)

        print("\n\n[*] Sweep complete. Waiting 3 seconds for delayed RF frames...")
        await asyncio.sleep(3.0)
        await client.stop_notify(NOTIFY_UUID)

    print("\n=======================================================")
    print("         DISCOVERED HARDWARE TELEMETRY MAP             ")
    print("=======================================================")
    if not discovered_telemetry:
        print("[-] No additional telemetry opcodes discovered.")
    else:
        for op, responses in sorted(discovered_telemetry.items()):
            print(f"  * Opcode 0x{op:02X} -> {len(responses)} response packet(s) captured.")
            print(f"    Sample Hex: {responses[0]}")
    print("=======================================================")

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n[!] Scanner aborted by user.")
    except Exception as err:
        print(f"\n[-] Execution Error: {err}")
