package com.watchify.app

val SPORT_TYPES = arrayOf(
    "Breathing",
    "Cycling",
    "Indoor Cycling",
    "Treadmill",
    "Running",
    "Swimming",
    "Walking",
    "Weightlifting",
    "Yoga",
    "Badminton",
    "Basketball",
    "Jump Rope",
    "Free Training",
    "Soccer",
    "Mountaineering",
    "Table Tennis",
    "Bowling",
    "Open Water Swimming",
    "Dancing",
    "Dumbbells",
    "Hula Hoop",
    "Stair Climber",
    "Stepper",
    "Triathlon",
    "Sit-ups",
    "Skiing",
    "Billiards",
    "Elliptical",
    "Trail Running",
    "Aerobics",
    "Pilates",
    "Shuttlecock",
    "Spinning",
    "Walking Machine",
    "Tennis",
    "Lower Body Training",
    "Upper Body Training",
    "Fencing",
    "Archery",
    "Barbell",
    "Muay Thai",
    "Parkour",
    "Rowing Machine",
    "Cricket",
    "Belly Dance",
    "Swordsmanship",
    "Other",
    "Judo",
    "Ice Skating",
    "Waist Training",
    "Latin Dance",
    "Flexibility",
    "Skateboarding",
    "Core Training",
    "Roller Skating",
    "Cross Training",
    "Core Strength",
    "Paragliding",
    "Kickboxing",
    "Medicine Ball",
    "Kabaddi",
    "Tug of War",
    "Baseball",
    "Fishing",
    "Gymnastics",
    "Snowboarding",
    "Boxing",
    "HIIT",
    "General Sports",
    "Volleyball",
    "American Football",
    "Ballet",
    "Bobsleigh",
    "Wrestling",
    "Power Walking",
    "Jazz Dance",
    "Sepak Takraw",
    "Frisbee",
    "Esports",
    "Martial Arts",
    "Physical Training",
    "Hip-hop",
    "Darts",
    "Sledding",
    "Rock Climbing",
    "Marathon",
    "Fitness",
    "Softball",
    "Bouldering",
    "Folk Dance",
    "Zumba",
    "Squash",
    "Kite Flying",
    "Motorsports",
    "Deadlifting",
    "Horse Riding",
    "ATV",
    "Tai Chi",
    "Square Dancing",
    "Beach Volleyball",
    "Karate",
    "Taekwondo",
    "Golf",
    "Curling",
    "Indoor Walking",
    "Beach Soccer",
    "Ice Hockey",
    "Field Hockey",
    "Burpees"
)
